slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: 'mapping'          # 'mapping' mode to build a map
    map_frame: 'map'
    odom_frame: 'odom'
    base_frame: 'base_link'
    # scan_topic: '/merged_scan'
    scan_topic: '/lidar_front/scan'
    resolution: 0.04
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    transform_publish_period: 0.05
    map_update_interval: 0.5
    scan_queue_size: 100
    throttle_scans: 1 
    provide_odom_frame: true
