slam_toolbox:
  ros__parameters:
    use_sim_time: false      # Set to true if you're simulating time
    mode: 'mapping'          # Important! 'mapping' or 'localization' or 'continue'
    map_frame: 'map'
    odom_frame: 'odom'
    base_frame: 'lidar1_link'  # or 'lidar1_link' or base_link
    scan_topic: '/lidar_front/scan'
    resolution: 0.04
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    transform_publish_period: 0.05
    map_update_interval: 3.0
    scan_queue_size: 100
    throttle_scans: 1 
    provide_odom_frame: true
    # If you have no real odometry, you might also need:
    # provide_odom_frame: false
    # publish_frame_projected_to_odom: false

    # publish_frame_projected_to_odom: false  # optional
