planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    controller_plugins: ["DWB"]
    DWB:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true

costmap_common_params:
  robot_radius: 0.3
  obstacle_range: 2.5
  raytrace_range: 3.0

global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 1.0
    static_map: true
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: "odom"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    plugins: ["obstacle_layer", "inflation_layer"]
